#ifndef USZRAM_PRIVATE_H
#define USZRAM_PRIVATE_H


#include "uszram.h"


#define BLK_PER_PG    (1 << (USZRAM_PAGE_SHIFT - USZRAM_BLOCK_SHIFT))
#define PG_ADDR_MAX   (USZRAM_BLK_ADDR_MAX / BLK_PER_PG)
#define LOCK_ADDR_MAX (PG_ADDR_MAX / USZRAM_PG_PER_LOCK)


#endif // USZRAM_PRIVATE_H
